using System.IO;
using System.Text;
using UnityEditor;

namespace OlegHcpEditor.CodeGenerating
{
    public static class GeneratingTools
    {
        public static void CreateCsFile(string text, string rootFolder, string className, string nameSpace, bool refreshAssets = true)
        {
            string dirPath = Path.Combine(rootFolder, $"{nameSpace.Replace('.', '/')}");
            Directory.CreateDirectory(dirPath);
            File.WriteAllText(dirPath + $"/{className}.cs", text, Encoding.UTF8);
            if (refreshAssets)
                AssetDatabase.Refresh();
        }

        public static void GenerateBanner(StringBuilder builder)
        {
            builder.AppendLine("///////////////////////////////////////")
                   .AppendLine("// Generated by script. Do not edit. //")
                   .AppendLine("///////////////////////////////////////");
        }
    }
}
